/* eslint-disable */
/**
 * Generated API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.5.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { ApiFromModules } from "convex/server"
import type * as fetchAvailableSlots from "../functions/fetchAvailableSlots"
import type * as createBooking from "../functions/createBooking"
import type * as handleGoogleCalendarUpdate from "../functions/handleGoogleCalendarUpdate"
import type * as handleGoogleCalendarDelete from "../functions/handleGoogleCalendarDelete"
import type * as sendBookingReminders from "../functions/sendBookingReminders"
import type * as listBookings from "../queries/listBookings"

/**
 * A type describing your app's public Convex API.
 *
 * This `API` type includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This is used to type-check usage of your API throughout your app.
 */
export type API = ApiFromModules<{
  "functions/fetchAvailableSlots": typeof fetchAvailableSlots
  "functions/createBooking": typeof createBooking
  "functions/handleGoogleCalendarUpdate": typeof handleGoogleCalendarUpdate
  "functions/handleGoogleCalendarDelete": typeof handleGoogleCalendarDelete
  "functions/sendBookingReminders": typeof sendBookingReminders
  "queries/listBookings": typeof listBookings
}>

/**
 * A type describing your app's public Convex API.
 *
 * This `api` object includes information about the arguments and return
 * types of your app's query and mutation functions.
 *
 * This is used to type-check usage of your API throughout your app.
 */
export const api = {
  functions: {
    fetchAvailableSlots: "functions/fetchAvailableSlots",
    createBooking: "functions/createBooking",
    handleGoogleCalendarUpdate: "functions/handleGoogleCalendarUpdate",
    handleGoogleCalendarDelete: "functions/handleGoogleCalendarDelete",
    sendBookingReminders: "functions/sendBookingReminders",
  },
  queries: {
    listBookings: "queries/listBookings",
  },
} as const
