/* eslint-disable */
/**
 * Generated data model types.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.5.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type { DataModelFromSchemaDefinition } from "convex/server"
import type bookings from "../schema/bookings"

/**
 * The names of all of your Convex tables.
 */
export type TableNames = "bookings"

/**
 * The type of the Convex data model.
 *
 * This type includes information about the document types and indexes in your
 * Convex database.
 */
export type DataModel = DataModelFromSchemaDefinition<{
  bookings: typeof bookings
}>
